# Generated by Django 4.2.6 on 2023-10-30 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='airline_name',
            new_name='city',
        ),
    ]
