# Generated by Django 4.2.6 on 2023-10-30 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_rename_airline_name_flight_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='airline_code',
            field=models.CharField(default='UNKNOWN', max_length=10),
        ),
        migrations.AddField(
            model_name='flight',
            name='airline_name',
            field=models.CharField(default='Unknown Airline', max_length=100),
        ),
        migrations.AddField(
            model_name='flight',
            name='departure_time',
            field=models.TimeField(default='00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flight',
            name='gate',
            field=models.CharField(default='UNKNOWN', max_length=10),
            preserve_default=False,
        ),
    ]
