# Generated by Django 4.2.6 on 2024-01-24 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=10)),
                ('airline_name', models.CharField(default='Unknown Airline', max_length=100)),
                ('airline_code', models.CharField(default='UNKNOWN', max_length=10)),
                ('city', models.CharField(choices=[('Toronto', 'Toronto'), ('Victoria', 'Victoria'), ('Montreal', 'Montreal'), ('Prince George', 'Prince George'), ('Winnipeg', 'Winnipeg'), ('Kelowna', 'Kelowna'), ('Fort McMurray', 'Fort McMurray'), ('Edmonton', 'Edmonton'), ('Whitehorse', 'Whitehorse'), ('Saskatoon', 'Saskatoon'), ('Vancouver', 'Vancouver'), ('Ottawa', 'Ottawa'), ('Halifax', 'Halifax'), ('Yellowknife', 'Yellowknife'), ('Comox', 'Comox'), ('Grande Prairie', 'Grande Prairie'), ('Lethbridge', 'Lethbridge'), ('Kamloops', 'Kamloops'), ('Medicine Hat', 'Medicine Hat')], max_length=100)),
                ('departure_time', models.TimeField()),
                ('gate', models.CharField(max_length=10)),
                ('airport_code', models.CharField(default='UNK', max_length=3)),
            ],
        ),
    ]
