# Generated by Django 4.2.6 on 2024-01-24 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='airport_code',
            new_name='airport_name',
        ),
    ]
